apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: social-app-clone-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: social-app.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: social-app-clone-service
            port:
              number: 80