apiVersion: v1
kind: Service
metadata:
  name: social-app-clone-service
spec:
  selector:
    app: social-app-clone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP