apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: social-app-clone
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nshivakumar1/social-app-clone.git
    targetRevision: HEAD
    path: k8s-manifests/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: social-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  revisionHistoryLimit: 10